spring.datasource.url=jdbc:postgresql://localhost:5432/university_db
spring.datasource.username=postgres
spring.datasource.password=****
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mongodb.uri=mongodb://localhost:27017/auth_db

server.port=8080

logging.level.org.springframework.jdbc.core=DEBUG
spring.data.mongodb.auto-index-creation=true